
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://michael.woolweaver.site"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Michael Woolweaver"
title: "{ Michael Woolweaver }"
description: "Michael Woolweaver's Compter Science Cruise."
keywords: "Woolweaver, Michael, blog, computer, science, macOS, iOS, Mac, iPhone"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Nothing today, Something tomorrow."
  - text: "Was today wasted if nothing new was learned?"

#me-img: "/img/jetpacktocat.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/mwoolweaver.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: False
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

#disqus-shortname: "michael.woolweaver.site"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/gce.png"
    date: " April 2019 "
    description: "Saving network overhead from the Cloud! An adventure with Pi-Hole on Google Compute Engine."
  - image: "/img/timeline/pihole.png"
    date: " November 2018 "
    description: "Saving network overhead! An adventure with Pi-Hole on Raspberry Pi 3B."
  - image: "/img/timeline/raspberry-pi.png"
    date: " September 2017 "
    description: "Starting down a rabbit hole! My first steps with a Raspberry Pi 3B."
  - image: "/img/timeline/linux.jpg"
    date: " December 2016 "
    description: "10 Operating System on one laptop. Because why not?!"
  - image: "/img/timeline/macows.jpg"
    date: " September 2015 "
    description: "Triple Booting my MacBookPro8,1, Learning to manage a hybrid MBR."
  - image: "/img/timeline/redsn0w.jpg"
    date: " August 2014 "
    description: "Jailbreaking the iPhone3,3, my love for tech was exposed."
  - image: "/img/timeline/bootcamp.png"
    date: " May 2013 "
    description: "Dual Booting my MacBookPro8,1, brought to you by BootCamp."
  - image: "/img/timeline/idroid.jpg"
    date: " December 2012 "
    description: "The iPhone 1,2, iDroid, & OpeniBoot."
  - image: "/img/timeline/Sn0wbreeze.png"
    date: " January 2011 "
    description: "The iPhone2,1 and bootom 359.3, technology has me hooked."
  - image: "/img/timeline/redsn0w.jpg"
    date: " December 2010 "
    description: "Jailbreaking the iPhone3,3, my love for tech was exposed."

# First image of the Timeline

timeline-img: "/img/timeline/begin.png"

###########
# Contact #
###########

email: "michael@woolweaver.site"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: ""
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  #- title: "facebook"
    #url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/m_woolweaver"
  - title: "github"
    url: "https://github.com/mwoolweaver"
  #- title: "bitcoin"
    #url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  #- title: "rss"
    #url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

#keybase-username: johnsmith
#keybase-in-social: True
#keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
